const Home = () =>{
    return (
        <div className="bg-[#0E1113] min-h-screen p-5">
            <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
             <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas ipsum unde illum, omnis rem voluptas dolor quisquam a quaerat repellat provident illo incidunt dolorem. Dolores molestiae cum officia accusamus suscipit?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga provident similique temporibus quas? Repellendus nostrum eligendi nemo, sapiente illum blanditiis voluptates vitae id et dolor quos officiis quibusdam iste. Voluptate. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facilis perspiciatis nemo illum reprehenderit, eveniet distinctio iusto unde similique atque consectetur quisquam ipsa quae, totam eaque obcaecati minima odit voluptates possimus!</span>
            
        </div>
    )
}

export default Home